package com.fjl.pojo;

public class systemAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.id
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.username
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.password
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.name
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_admin.telephone
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    private String telephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.id
     *
     * @return the value of system_admin.id
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.id
     *
     * @param id the value for system_admin.id
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.username
     *
     * @return the value of system_admin.username
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.username
     *
     * @param username the value for system_admin.username
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.password
     *
     * @return the value of system_admin.password
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.password
     *
     * @param password the value for system_admin.password
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.name
     *
     * @return the value of system_admin.name
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.name
     *
     * @param name the value for system_admin.name
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_admin.telephone
     *
     * @return the value of system_admin.telephone
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_admin.telephone
     *
     * @param telephone the value for system_admin.telephone
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }
}