package com.fjl.mapper;

import com.fjl.pojo.dormitoryAdmin;
import com.fjl.pojo.dormitoryAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface dormitoryAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int countByExample(dormitoryAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int deleteByExample(dormitoryAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int insert(dormitoryAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int insertSelective(dormitoryAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    List<dormitoryAdmin> selectByExample(dormitoryAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    dormitoryAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") dormitoryAdmin record, @Param("example") dormitoryAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int updateByExample(@Param("record") dormitoryAdmin record, @Param("example") dormitoryAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int updateByPrimaryKeySelective(dormitoryAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int updateByPrimaryKey(dormitoryAdmin record);
}