package com.fjl.mapper;

import com.fjl.pojo.systemAdmin;
import com.fjl.pojo.systemAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface systemAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int countByExample(systemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int deleteByExample(systemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int insert(systemAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int insertSelective(systemAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    List<systemAdmin> selectByExample(systemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    systemAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") systemAdmin record, @Param("example") systemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int updateByExample(@Param("record") systemAdmin record, @Param("example") systemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int updateByPrimaryKeySelective(systemAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_admin
     *
     * @mbggenerated Thu Oct 20 14:32:47 CST 2022
     */
    int updateByPrimaryKey(systemAdmin record);
}